---
name: nebula
version: dev
slug: nebula
description: Radically simplify your network with a virtual networking layer that works the same everywhere
url: https://github.com/hassio-addons/addon-nebula
codenotary: codenotary@
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  4242/udp: 4242
ports_description:
  4242/udp: Nebula's primary port
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/net/tun
#map:
#  - ssl:rw
options:
  host_key: ""
  host_cert: ""
  ca_cert: ""
  config: ""
schema:
  host_key: str
  host_cert: str
  ca_cert: str
  config: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
